// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBlmZnl17M1L5p-5F_r4hBLyoKVkcWKo',
    appId: '1:492285547475:web:7abf0269322bb47249d526',
    messagingSenderId: '492285547475',
    projectId: 'mynotes-taufiqidr',
    authDomain: 'mynotes-taufiqidr.firebaseapp.com',
    storageBucket: 'mynotes-taufiqidr.appspot.com',
    measurementId: 'G-RKSD79N96B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhssKrBeN9aHYklfTEwM7wnVvMD0EJnw',
    appId: '1:492285547475:android:9a74f77a0b45de0949d526',
    messagingSenderId: '492285547475',
    projectId: 'mynotes-taufiqidr',
    storageBucket: 'mynotes-taufiqidr.appspot.com',
  );
}
